nelmio_api_doc:
    documentation:
        info:
            title: API du  Club de tir du Pays Loudonnais (CTPL)
            description: Application permettent d'aider à la gestion du club de tir de loudun
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
